services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banking_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5

  banking-api-data-migrations:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: banking_api_data_migrations
    env_file:
      - ./src/config.docker.yaml
    depends_on:
      db:
        condition: service_healthy
    networks:
      - banking_network
    volumes:
      - ./src:/app/src
      - ./src/config.docker.yaml:/app/config.yaml
    command: ["./banking-api", "migrate"]

  banking-api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: banking_api
    env_file:
      - ./src/config.docker.yaml
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      banking-api-data-migrations:
        condition: service_completed_successfully
    networks:
      - banking_network
    volumes:
      - ./src:/app/src
      - ./src/config.docker.yaml:/app/config.yaml
    command: ["./banking-api", "serve_api"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT}/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - banking_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  banking_network:
    driver: bridge

volumes:
  db_data:
    driver: local