Server:
  Port: 8080
  ReadTimeout: 30s
  WriteTimeout: 30s
  IdleTimeout: 60s
  MaxConnections: 100
  ShutdownTimeout: 30  # Graceful shutdown timeout in seconds
  Environment: development  # development, production

Database:
  Host: localhost
  Port: 3306
  Username: banking_user
  Password: userpassword
  Name: banking
  MaxOpenConns: 100
  MaxIdleTimeInSecond: 30

Redis:
  # Single instance configuration
  Host: localhost
  Port: 6379
  Password: redispassword
  DB: 0
  MaxIdle: 10
  IdleTimeout: 240s
  
  # Sentinel configuration (set UseSentinel to true to enable)
  UseSentinel: false
  SentinelAddrs:
    - "localhost:26379"
    - "localhost:26380"
    - "localhost:26381"
  SentinelPassword: ""
  MasterName: "mymaster"

Logger:
  Level: info           # debug, info, warn, error
  LogColor: true        # true or false
  LogJson: false        # true or false

Auth:
  Jwt:
    AccessTokenSecret: banking-api-access-secret-key-change-in-production
    RefreshTokenSecret: banking-api-refresh-secret-key-change-in-production
    AccessTokenExpiry: 5 # in minutes
    RefreshTokenExpiry: 7 # in days

  Pin:
    BaseDuration: 10s      # Base duration for PIN lock (e.g., 10s, 1m, 5m)
    MaxLockDuration: 300s  # Maximum lock duration (e.g., 300s, 5m, 10m)
    LockThreshold: 3       # Number of failed attempts before lock