Server:
  Port: 8080
  ReadTimeout: 30s
  WriteTimeout: 30s
  IdleTimeout: 60s
  MaxConnections: 100
  ShutdownTimeout: 30  # Graceful shutdown timeout in seconds
  Environment: production  # development, production

Database:
  Host: mysql_db
  Port: 3306
  Username: banking_user
  Password: userpassword
  Name: banking
  MaxOpenConns: 100
  MaxIdleTimeInSecond: 30

Redis:
  Host: redis
  Port: 6379
  Password: redispassword
  DB: 0
  MaxIdle: 10
  IdleTimeout: 240s
  
Logger:
  Level: info           # debug, info, warn, error
  LogColor: true        # true or false
  LogJson: false        # true or false

Auth:
  Jwt:
    AccessTokenSecret: banking-api-access-secret-key-change-in-production
    RefreshTokenSecret: banking-api-refresh-secret-key-change-in-production
    AccessTokenExpiry: 5 # in minutes
    RefreshTokenExpiry: 7 # in days

  Pin:
    BaseDuration: 10s
    MaxLockDuration: 300s
    LockThreshold: 3