Server:
  Port: 8080
  ReadTimeout: 30s
  WriteTimeout: 30s
  IdleTimeout: 60s
  MaxConnections: 100
  ShutdownTimeout: 30  # Graceful shutdown timeout in seconds
  Environment: development  # development, production

Database:
  Host: mysql_db
  Port: 3306
  Username: banking_user
  Password: userpassword
  Name: banking
  MaxOpenConns: 100
  MaxIdleTimeInSecond: 30

Logger:
  Level: info           # debug, info, warn, error
  LogColor: true        # true or false
  LogJson: false        # true or false